services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

  postgresdb:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
